version: "3.4"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=eco
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 85:80
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  chatbot-mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
